spec:
  structures: [content_blocks]
  label: Two Column
  description: A layout block with two columns, each containing blocks.
  icon: view_column
blueprint:
  blocks: [bookshop:structure:content_blocks]
  side: left

_inputs:
  blocks:
    side:
      type: select
      label: Side
      options:
        values:
          - left
          - right
