spec:
  label: Two Column
  description: A layout block with two columns, each containing blocks.
  icon: view_column
blueprint:
  left_blocks: [bookshop:structure:content_blocks]
  right_blocks: [bookshop:structure:content_blocks] 